### ISSUE TITLE
async-fp context :)

### ISSUE THREAD

**Issue by unional** [BorderlessLabs/context#1]
Hi Blake, just FYI maybe you will be interested in the `AsyncContext` I have in [`async-fp`](https://github.com/unional/async-fp).

🌷

**Comment by blakeembrey** [comment]
Nice! That looks interesting and there's some overlap here. 

How do you like having the `Context` values typed? It's one of the design choices I couldn't decide either way, but I went the other direction and didn't type the values in arguments at all (instead dependencies will use module augmentation to add to the values, and `get` can always return `undefined`).

**Comment by unional** [comment]
I have the type of the value defined at creation (`new AsyncContext<T>()` or inferred).
`context.set()` is just setting the value, not adding things to it.
For adding,  you can use `context.merge()` which creates a new context with union type.
i.e. `context<T>.merge<R>(): AsyncContext<LeftJoin<T, R>>`

I designed it like this because I use it as the context variable in functional styled programming like:

```ts
function foo(context, ...) {
  return boo(context, ...)
}
function boo(context, ...) {
  return koo(context, ...)
}
```

So `set()` typically only occurs once.
And it can be only once because you can `Promise.all()` your dependencies before calling `set()`.

Here is a cool use case of it:
https://github.com/mocktomata/mocktomata/blob/b00c0bdd3c8fca549f41371484dc4ac2e53a9225/packages/framework/src/mockto/createMockto.ts#L30-L33

I'm also considering adding a `transform()` function so that `context<T>.transform<R>(): AsyncContext<R>` to support simple override/replacement.

**Comment by blakeembrey** [comment]
Thanks @unional. I ended up refactoring a bit more and it looks much more like Go now, with the type safety of TypeScript everywhere. I also added a standard abort method (using promises) which mimics the native done channel in Go also. Not convinced it's the best way to do cancellation in JS, but it's lighter than an event emitter (e.g. `AbortController`) and works nicely with things like `Promise.race([])`.

**Comment by unional** [comment]
Cool. The `withAbort()` is interesting. I also want to add the abort and timeout mechanism to mine.

I like the Go syntax also. I do find the `try/catch` is too verbose.

btw, there is a interesting code related to try/catch:

```ts
export function captureLogs(logger: Logger, funcBlock: Function): LogEntry[] | Promise<LogEntry[]> {
  const reporter = createMemoryLogReporter()
  addRedirects(logger.id, reporter)
  try {
    const result = funcBlock()
    if (isPromise(result)) {
      return result.then(() => reporter.logs)
        .finally(() => removeRedirects(logger.id, reporter))
    }
    return reporter.logs
  }
  finally {
    removeRedirects(logger.id, reporter)
  }
}
```

There is a bug in this code. :)

After I talking to you, I ended up do some refactoring and redesigned the `AsyncContext` API.

Want to ask a small favor of you.
Can you give me some feedback about the README I wrote for `AsyncContext`?

https://github.com/unional/async-fp/tree/master/packages/async-context

I want to know if I was able to describe it clearly and effectively,
so people can understand and use the library.

Thanks! 🌷

**Comment by unional** [comment]
I feel like my README in general are pretty bad.

**Comment by blakeembrey** [comment]
@unional It makes sense, though it's not clear why I'd want `initialize` and the constructor style. The less ways of doing something the better. There's a small typo in that heading too.

As for that bug, yeah, mixing async and sync code is never fun.

**Comment by blakeembrey** [comment]
I'm also not sure why I might want the lazy resolver by default? Maybe there's a good reason for that?

**Comment by blakeembrey** [comment]
Also, if you think immutability is something you'd want, just use `Object.freeze`: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/freeze. I think it'd cover your use-case, though I'm not sure of the perf overhead.

**Comment by unional** [comment]
Thanks for the feedback!

> I'd want initialize and the constructor style.
This enable to use case of defining the context in one place and have it initialize in another. e.g the context is defined in the application partition, and initialized in the main partition (Uncle Bob way of saying the application vs where you inject the dependency).
I can force using the `initialize()` and remove the constructor argument, but then I have to always define the type and can't get the type inference work for me in other use cases.

> why I might want the lazy resolver by default? 
In the previous version I do have immediate resolution as default and add an option to be lazy (`{ lazy: true }`). 
But in my use case I find that lazy resolution is much more powerful (e.g. the `Inject Configuration` example), and likely the more common usage, so I flip that.
Also I realize if user want to kick off the dependency loading, they can start resolving the dependency and pass a promise to the `constructor()/initialize()/extend()` methods.

But yeah, I might add an option back in later on. :)

> Also, if you think immutability is something you'd want, just use Object.freeze

Do you mean ask user to do that instead of using `immutable`? That's probably a good idea. thx. 👍 

> not sure of the perf overhead.
I think there is not much of a difference:
https://stackoverflow.com/questions/8435080/any-performance-benefit-to-locking-down-javascript-objects


Again, many thanks!

**Comment by unional** [comment]
> There's a small typo in that heading too.

Where is the typo? I'm blind. 😛

**Comment by unional** [comment]
Really appreciate your feedback. The questions you have are likely questions other people will have.
So I should find some way to improve the design and the doc. :)

**Comment by unional** [comment]
> Where is the typo? I'm blind. 😛

Found it `Initialze`

**Comment by unional** [comment]
Just realize maybe I can further simplify it by exposing a singleton and just use `extend()`.
Kind of like your `background`.
